---
- name: reload systemd
  listen: reload riemann agents
  shell: systemctl --system daemon-reload

- name: restart services
  listen: restart riemann agents
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - "{{ riemann_systemd_plugins }}"
