---
- name: reload riemann_health
  shell: systemctl --system daemon-reload
  notify: restart riemann-health

- name: restart riemann-health
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - "{{ riemann_systemd_plugins }}"